### ISSUE TITLE
Remove weekends

### ISSUE THREAD

**Issue by louishugens** [nyura123/react-availability-calendar#4]
Hello,

How do we remove weekends from booking availabilities? Thanks

**Comment by nyura123** [comment]
@louishugens I have added `excludeWeekends` option to the calendar, available in version 0.3.13.
Also you now have an optional `excludeFn` prop which takes a Date and returns a boolean to exclude it. To exclude wednesdays for example: `excludeFn={d => d.getDay() === 3}`

**Comment by louishugens** [comment]
This is awesome. Thank you so much. Maybe you should update the
documentation. Thanks again.
Best Regards
Hugens LOUIS
(+509)-47007622

**Comment by nyura123** [comment]
@louishugens glad you find it useful! I'll add more documentation later but for now it's documented via the `AvailabilityCalendarProps` section.
